[package]
name = "gdua-core"
version = "0.1.0"
authors = ["pbzweihander <pbzweihander@gmail.com>"]
edition = "2018"

[dependencies]
tokio = "0.1.15"
tokio-fs = "0.1.5"
futures = "0.1.25"
failure = "0.1.5"
