[package]
name = "gdua-ui"
version = "0.1.0"
authors = ["pbzweihander <pbzweihander@gmail.com>"]
edition = "2018"

[dependencies]
yew = { git = "https://github.com/DenisKolodin/yew", branch = "master" }
stdweb = "0.4.14"
